<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>0.6.0</Version>
    <AssemblyVersion>0.6.0</AssemblyVersion>
    <FileVersion>0.6.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="_dump_*.cs" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
  <Import Project="$(MSBuildThisFileDirectory)valheim.targets" />
</Project>
